
model_params:
  common_params:
    num_kp: 10
  kp_detector_params:
     num_channels: 1
     estimate_jacobian: True
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     scale_factor: 0.25
     num_blocks: 5
     single_jacobian_map: True
  generator_params:
    estimate_jacobian: True
    dense_motion_params:
      num_channels: 4
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25

train_params:
  lr_generator: 2.0e-4
  lr_kp_detector: 2.0e-4
  transform_params:
    sigma_affine: 0.04
    sigma_tps: 0.005
    points_tps: 8
  loss_weights:
    equivariance_value: 5
    equivariance_jacobian: 5
